version: "3"
services:
  # frontend:
  #   build: ./frontend
  #   container_name: frontend_container
  #   stdin_open: true
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - ecommerce-app
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules

  order_service:
    build: ./order_service
    container_name: order_service_container
    ports:
      - "5006:5006"
    networks:
      - ecommerce-app
    links:
      - order_db
    restart: on-failure
    depends_on:
      - order_db
    volumes:
      - ./order_service:/app
      - /app/node_modules

  users_service:
    build: ./users_service
    container_name: users_service_container
    ports:
      - "5000:5000"
    networks:
      - ecommerce-app
    links:
      - users_db
    restart: on-failure
    depends_on:
      - users_db
    volumes:
      - ./users_service:/app
      - /app/node_modules

  cart_service:
    build: ./cart_service
    container_name: cart_service_container
    ports:
      - "5001:5001"
    networks:
      - ecommerce-app
    links:
      - cart_db
    restart: on-failure
    depends_on:
      - cart_db
    volumes:
      - ./cart_service:/app
      - /app/node_modules

  products_service:
    build: ./products_service
    container_name: products_service_container
    ports:
      - "5002:5002"
    networks:
      - ecommerce-app
    links:
      - products_db
    restart: on-failure
    depends_on:
      - products_db
    volumes:
      - ./products_service:/app
      - /app/node_modules

  payment_service:
    build: ./payment_service
    container_name: payment_service_container
    ports:
      - "5003:5003"
    networks:
      - ecommerce-app
    links:
      - payment_db
    restart: on-failure
    depends_on:
      - payment_db
    volumes:
      - ./payment_service:/app
      - /app/node_modules

  cart_db:
    image: mongo:3.6.19-xenial
    ports:
      - "27019:27017"
    networks:
      - ecommerce-app
    volumes:
      - cart-volume:/data/db

  order_db:
    image: mongo:3.6.19-xenial
    ports:
      - "27018:27017"
    networks:
      - ecommerce-app
    volumes:
      - order-volume:/data/db

  users_db:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - ecommerce-app
    volumes:
      - users-volume:/data/db

  products_db:
    image: mongo:3.6.19-xenial
    ports:
      - "27020:27017"
    networks:
      - ecommerce-app
    volumes:
      - products-volume:/data/db

  payment_db:
    image: mongo:3.6.19-xenial
    ports:
      - "27021:27017"
    networks:
      - ecommerce-app
    volumes:
      - payment-volume:/data/db

networks:
  ecommerce-app:
    driver: bridge
volumes:
  order-volume:
    driver: local
  users-volume:
    driver: local
  cart-volume:
    driver: local
  products-volume:
    driver: local
  payment-volume:
    driver: local
