version: "3"
services:
  frontend:
    build: ./frontend
    container_name: frontend_container
    stdin_open: true
    ports:
      - "8080:8080"
    networks:
      - ecommerce-app
    volumes:
      - ./frontend:/app
      - /app/node_modules
  order_service:
    build: ./order_service
    container_name: order_service_container
    ports:
      - "5006:5006"
    networks:
      - ecommerce-app
    links:
      - order_db
    restart: on-failure
    depends_on:
      - order_db
    volumes:
      - ./order_service:/app
      - /app/node_modules
  users_service:
    build: ./users_service
    container_name: users_service_container
    ports:
      - "5000:5000"
    networks:
      - ecommerce-app
    links:
      - users_db
    restart: on-failure
    depends_on:
      - users_db
    volumes:
      - ./users_service:/app
      - /app/node_modules
  order_db:
    image: mongo:3.6.19-xenial
    ports:
      - "27018:27017"
    networks:
      - ecommerce-app
    volumes:
      - order-volume:/data/db
  users_db:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - ecommerce-app
    volumes:
      - users-volume:/data/db
networks:
  ecommerce-app:
    driver: bridge
volumes:
  order-volume:
    driver: local
  users-volume:
    driver: local
